### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by fr-an-k** [StarLederer/vite-plugin-fs#15]
I followed the readme but get this error (node 18.14.0).
I'm using yarn (1.22.19) but pnpm fails too.

[ERROR] [plugin externalize-deps] Failed to resolve entry for package "vite-plugin-fs". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "vite-plugin-fs" package

**Comment by StarLederer** [comment]
I will double check later today but I have one theory right now that you might be able to try right away. There is a chance this is caused by the lack of CJS support so check if you are using CJS or ESM, having (or not having) `"type": "module"` in your package.json should be a good indicator of which one you use

**Comment by StarLederer** [comment]
Confirmed there is a problem, reproduces very easily, will need to check if Vite changed something so it is not compatible with newer version

**Comment by StarLederer** [comment]
Should be fixed in 1.0.0-beta.6. Please try it and confirm that the problem has been resolved. I'll keep the issue open until I have your confirmation

**Comment by fr-an-k** [comment]
Thanks, it works!
(I noticed that the beta.6 was installed by default, just a heads up)
